export const CATALOG = [
  {
    id: 'minerals', label: 'Minerals & Electrolytes',
    products: [
      { id: 'ionic-mineral-complex', name: 'Ionic Mineral Complex', sku: 'ROC720', price: '$29.95', size: '2 fl oz',
        shopifyHandle: 'ionic-mineral-complex-trace-mineral-drops-2-fl-oz',
        chips: ['What minerals are inside?','Is it vegan & gluten-free?','How do I use it daily?','What health benefits?','Price & servings?'],
        context: `Product: Ionic Mineral Complex Trace Mineral Drops\nSKU: ROC720 | Price: $29.95 | Size: 2 fl oz | Unit Price: $5.99/oz\nDescription: All-natural liquid concentrate replenishing key trace minerals modern diets lack. Broad-spectrum ionic formula, 99% sodium removed.\nSupplement Facts (per 1/2 tsp / 2.5mL, 21 servings):\n- Magnesium: 180mg (43% DV)\n- Chloride: 620mg (27% DV)\n- Sodium: 15mg (<1% DV)\n- Sulfate: 11mg\n- Sulfur: 18mg\n- Lithium: 740mcg\n- Boron: 270mcg\nIngredient: Ionic Trace Mineral Concentrate (99% sodium removed)\nKey Benefits: Broad-spectrum ionic minerals, maximum absorption liquid, hydration, nerve & muscle function, bone & joint, digestive health, heart health, energy & metabolism. Unflavored.\nSuggested Use: Mix 1/2 tsp daily in 1L water or juice. Sensitive users start with 1/4 tsp in 2L. Do not take undiluted.\nCertifications: Organic, Vegan, Vegetarian, Gluten-Free, Non-GMO, Keto-friendly, GMP-compliant.\nWarnings: Consult healthcare professional if pregnant, nursing, on medication, or managing a medical condition. Keep out of reach of children.` },
      { id: 'magnesium-glycinate', name: 'Magnesium Glycinate', sku: 'ROC721', price: '$34.95', size: '120 capsules',
        shopifyHandle: 'magnesium-glycinate',
        chips: ['Why glycinate form?','Best time to take?','Sleep benefits?','Muscle recovery?','Capsule ingredients?'],
        context: `Product: Magnesium Glycinate\nSKU: ROC721 | Price: $34.95 | Size: 120 capsules | 60 servings\nDescription: Highly bioavailable magnesium bound to glycine for superior absorption vs magnesium oxide. Gentle on the stomach.\nSupplement Facts (per 2 capsules):\n- Magnesium (as Bisglycinate Chelate): 400mg (95% DV)\nOther: Vegetable cellulose capsule, microcrystalline cellulose.\nKey Benefits: Superior absorption, promotes relaxation and quality sleep, muscle recovery, reduces stress, bone density, heart rhythm support.\nSuggested Use: Take 2 capsules daily. Best in the evening for sleep support.\nCertifications: Vegan, Gluten-Free, Non-GMO, GMP-compliant.\nWarnings: Do not exceed recommended dose. Consult healthcare professional if pregnant or on medication.` },
      { id: 'electrolyte-blend', name: 'Electrolyte Hydration Blend', sku: 'ROC722', price: '$27.95', size: '30 stick packs',
        shopifyHandle: 'electrolyte-hydration-blend',
        chips: ['Is there any sugar?','Best time to drink?','Good for keto?','How much sodium?','What flavor?'],
        context: `Product: Electrolyte Hydration Blend\nSKU: ROC722 | Price: $27.95 | Size: 30 stick packs\nDescription: Clean electrolyte formula with no artificial sweeteners, colors, or flavors.\nSupplement Facts (per 1 stick):\n- Sodium: 300mg (13% DV)\n- Potassium: 200mg (4% DV)\n- Magnesium: 60mg (14% DV)\n- Chloride: 460mg (20% DV)\n- Calcium: 50mg (4% DV)\nOther: Organic coconut water powder, pink Himalayan salt, natural lemon-lime flavor.\nKey Benefits: Rapid electrolyte replenishment, zero sugar, athletic performance, prevents cramps, natural lemon-lime flavor.\nSuggested Use: Mix 1 stick in 12-16 oz water before, during, or after exercise.\nCertifications: Organic, Vegan, Gluten-Free, Non-GMO, Keto-friendly.\nWarnings: Monitor sodium if on a low-sodium diet.` }
    ]
  },
  {
    id: 'vitamins', label: 'Vitamins & Immunity',
    products: [
      { id: 'vitamin-d3-k2', name: 'Vitamin D3 + K2', sku: 'ROC730', price: '$24.95', size: '90 softgels',
        shopifyHandle: 'vitamin-d3-k2',
        chips: ['Why D3 + K2 together?','Is it vegan?','Safe D3 dose?','Bone health benefits?','Blood thinner interaction?'],
        context: `Product: Vitamin D3 + K2\nSKU: ROC730 | Price: $24.95 | Size: 90 softgels\nDescription: Synergistic D3 and K2 (MK-7) combination. D3 enhances calcium absorption; K2 directs it to bones and away from arteries. Delivered in organic olive oil.\nSupplement Facts (per 1 softgel):\n- Vitamin D3 (Cholecalciferol): 5000 IU (1250% DV)\n- Vitamin K2 (MK-7, Menaquinone-7): 100mcg\nOther: Organic olive oil, gelatin softgel, sunflower lecithin.\nKey Benefits: Bone density, immune support, cardiovascular health, mood and seasonal wellness, muscle function.\nSuggested Use: Take 1 softgel daily with a fat-containing meal.\nCertifications: Non-GMO, Gluten-Free, GMP-compliant. Contains gelatin - NOT vegan.\nWarnings: Do not exceed 10,000 IU D3 daily without medical supervision. K2 may interact with warfarin.` },
      { id: 'liposomal-vitamin-c', name: 'Liposomal Vitamin C', sku: 'ROC731', price: '$39.95', size: '60 capsules',
        shopifyHandle: 'liposomal-vitamin-c',
        chips: ['What is liposomal?','Better than regular Vitamin C?','Immune benefits?','Skin & collagen?','Serving size?'],
        context: `Product: Liposomal Vitamin C\nSKU: ROC731 | Price: $39.95 | Size: 60 capsules | 30 servings\nDescription: Advanced liposomal delivery encapsulates ascorbic acid in phospholipid liposomes for up to 90% absorption vs ~20% for standard Vitamin C.\nSupplement Facts (per 2 capsules):\n- Vitamin C (Liposomal Ascorbic Acid): 1000mg (1111% DV)\n- Phosphatidylcholine (sunflower lecithin): 400mg\nOther: Vegetable cellulose capsule. Soy-free.\nKey Benefits: Superior absorption, immune defense, collagen synthesis, antioxidant protection, adrenal support.\nSuggested Use: Take 2 capsules daily on empty stomach or light meal. May increase to 4 during illness.\nCertifications: Vegan, Gluten-Free, Non-GMO, Soy-Free, GMP-compliant.\nWarnings: Doses above 4g/day may cause digestive discomfort. Consult doctor if on anticoagulants.` },
      { id: 'zinc-bisglycinate', name: 'Zinc Bisglycinate', sku: 'ROC732', price: '$19.95', size: '60 capsules',
        shopifyHandle: 'zinc-bisglycinate',
        chips: ['Why bisglycinate form?','Good for immune?','Skin and acne?','Safe daily amount?','Take with food?'],
        context: `Product: Zinc Bisglycinate\nSKU: ROC732 | Price: $19.95 | Size: 60 capsules | 60 servings\nDescription: Zinc bound to two glycine molecules for gentle, highly absorbable delivery with minimal GI side effects vs zinc sulfate or oxide.\nSupplement Facts (per 1 capsule):\n- Zinc (as Bisglycinate): 25mg (227% DV)\nOther: Vegetable cellulose capsule only. No fillers.\nKey Benefits: Immune function, wound healing, skin health and acne reduction, testosterone support, taste and smell, antioxidant enzyme activity.\nSuggested Use: Take 1 capsule daily with food.\nCertifications: Vegan, Gluten-Free, Non-GMO, GMP-compliant, No fillers.\nWarnings: Do not exceed 40mg zinc daily. Long-term use may deplete copper.` }
    ]
  },
  {
    id: 'cognitive', label: 'Cognitive & Mood',
    products: [
      { id: 'lions-mane', name: "Lion's Mane Mushroom", sku: 'ROC740', price: '$44.95', size: '60 capsules',
        shopifyHandle: 'lions-mane-mushroom-extract',
        chips: ['What is NGF?','Memory benefits?','How long to feel effects?','Fruiting body vs mycelium?','Mood support?'],
        context: `Product: Lion's Mane Mushroom Extract\nSKU: ROC740 | Price: $44.95 | Size: 60 capsules | 30 servings\nDescription: Dual-extracted (hot water + alcohol) Lion's Mane (Hericium erinaceus) capturing full-spectrum hericenones and erinacines that support nerve growth factor (NGF) synthesis. Fruiting body only.\nSupplement Facts (per 2 capsules):\n- Lion's Mane Extract (fruiting body, 8:1 concentrate, 30% polysaccharides): 1000mg\nOther: Vegetable cellulose capsule only.\nKey Benefits: NGF support, cognitive clarity and focus, memory and learning, mood balance, neuroprotective properties.\nSuggested Use: Take 2 capsules daily. Best results after 4-8 weeks consistent use.\nCertifications: Vegan, Gluten-Free, Non-GMO, Organic, GMP-compliant. Fruiting body only.\nWarnings: Rare mushroom allergy possible. Consult doctor if on blood thinners or diabetic medication.` },
      { id: 'ashwagandha', name: 'Ashwagandha KSM-66', sku: 'ROC741', price: '$32.95', size: '60 capsules',
        shopifyHandle: 'ashwagandha-ksm-66',
        chips: ['What is KSM-66?','Stress & cortisol?','Sleep benefits?','Athletic performance?','Safe for thyroid?'],
        context: `Product: Ashwagandha KSM-66\nSKU: ROC741 | Price: $32.95 | Size: 60 capsules | 30 servings\nDescription: Full-spectrum ashwagandha root extract standardized to 5% withanolides via KSM-66 — the most clinically studied ashwagandha with 24+ human clinical trials.\nSupplement Facts (per 2 capsules):\n- Ashwagandha Root Extract KSM-66 (5% withanolides): 600mg\n- Organic Black Pepper Extract (BioPerine, 95% piperine): 5mg\nOther: Vegetable cellulose capsule only.\nKey Benefits: Stress and cortisol reduction, improved sleep onset, testosterone and athletic performance, thyroid support, enhanced endurance and VO2 max.\nSuggested Use: Take 2 capsules daily. Take both 1 hour before bed for sleep support.\nCertifications: Vegan, Gluten-Free, Non-GMO, Organic, GMP-compliant, KSM-66 certified.\nWarnings: May lower thyroid hormones — consult doctor if on thyroid medication. Avoid if pregnant.` },
      { id: 'b-complex', name: 'B-Complex Complete', sku: 'ROC742', price: '$28.95', size: '60 capsules',
        shopifyHandle: 'b-complex-complete',
        chips: ['What is methylfolate?','MTHFR gene?','Energy benefits?','Hair & skin?','Why yellow urine?'],
        context: `Product: B-Complex Complete\nSKU: ROC742 | Price: $28.95 | Size: 60 capsules | 30 servings\nDescription: Comprehensive B-vitamin formula using active/methylated forms. Includes methylfolate (not folic acid) and methylcobalamin (not cyanocobalamin) — essential for those with MTHFR gene variants.\nSupplement Facts (per 2 capsules):\n- B1 (Thiamine HCl): 50mg\n- B2 (Riboflavin): 25mg\n- B3 (Niacinamide): 100mg\n- B5 (Pantothenic Acid): 100mg\n- B6 (Pyridoxal-5-Phosphate): 25mg\n- B7 (Biotin): 1000mcg\n- B9 (5-MTHF Methylfolate): 800mcg\n- B12 (Methylcobalamin): 1000mcg\nOther: Vegetable cellulose capsule only.\nKey Benefits: Cellular energy production, nervous system health, mood support, hair/skin/nail health, methylation cycle, red blood cell formation.\nSuggested Use: Take 2 capsules daily with food. Riboflavin causes harmless bright yellow urine.\nCertifications: Vegan, Gluten-Free, Non-GMO, GMP-compliant. MTHFR-safe.\nWarnings: Niacin flush possible. Consult doctor if on metformin.` }
    ]
  },
  {
    id: 'digestive', label: 'Digestive Health',
    products: [
      { id: 'probiotic', name: 'Probiotic 50B CFU', sku: 'ROC750', price: '$49.95', size: '30 capsules',
        shopifyHandle: 'probiotic-50-billion-cfu',
        chips: ['10 strains vs fewer?','Need refrigeration?','Help with IBS?','After antibiotics?','What is prebiotic FOS?'],
        context: `Product: Probiotic 50 Billion CFU\nSKU: ROC750 | Price: $49.95 | Size: 30 capsules | 30 servings\nDescription: Multi-strain probiotic with 50 billion CFU across 10 clinically validated strains. Delayed-release capsule ensures survival through stomach acid. Shelf-stable before opening.\nSupplement Facts (per 1 capsule):\n- Probiotic Blend 50B CFU: Lactobacillus acidophilus, L. plantarum, L. rhamnosus, L. paracasei, L. casei, Bifidobacterium longum, B. breve, B. bifidum, B. lactis, Streptococcus thermophilus\n- Prebiotic FOS: 100mg\nOther: Delayed-release vegetable capsule.\nKey Benefits: Gut microbiome balance, IBS and bloating relief, immune support, improved regularity, reduces antibiotic-associated diarrhea.\nSuggested Use: Take 1 capsule daily. Refrigerate after opening. Take 2 after antibiotics or when traveling.\nCertifications: Vegan, Gluten-Free, Non-GMO, GMP-compliant. Shelf-stable before opening.\nWarnings: Mild bloating possible in first 1-2 weeks. Consult doctor if immunocompromised.` },
      { id: 'digestive-enzymes', name: 'Digestive Enzyme Complex', sku: 'ROC751', price: '$36.95', size: '60 capsules',
        shopifyHandle: 'digestive-enzyme-complex',
        chips: ['What enzymes are included?','Help with lactose?','Bloating & gas?','Take before meals?','Plant vs animal enzymes?'],
        context: `Product: Digestive Enzyme Complex\nSKU: ROC751 | Price: $36.95 | Size: 60 capsules | 30 servings\nDescription: Full-spectrum plant-derived digestive enzyme formula covering all major macronutrients. Works across broad pH range unlike animal-derived pancreatin.\nSupplement Facts (per 2 capsules):\n- Amylase: 15,000 DU (carbohydrates)\n- Protease Blend: 80,000 HUT (proteins)\n- Lipase: 3,000 FIP (fats)\n- Lactase: 3,000 ALU (lactose)\n- Cellulase: 600 CU (plant fiber)\n- Alpha-Galactosidase: 300 GalU (beans, legumes)\n- Bromelain (pineapple): 2,400 GDU\n- Papain (papaya): 1,500 PU\nOther: Vegetable cellulose capsule only.\nKey Benefits: Reduced bloating and gas, improved protein absorption, lactose intolerance support, better nutrient extraction.\nSuggested Use: Take 2 capsules immediately before each meal.\nCertifications: Vegan, Gluten-Free, Non-GMO, GMP-compliant. Plant-derived.\nWarnings: Not for active stomach ulcers. Bromelain/papain may interact with blood thinners.` }
    ]
  }
]
